stages:
  - test
  - release

lint:
  stage: test
  only: ['main']
  image: registry.gitlab.com/etke.cc/base
  script:
    - make lint

unit:
  stage: test
  only: ['main']
  image: registry.gitlab.com/etke.cc/base
  script:
    - make test

docker:
  stage: release
  only: ['main', 'tags']
  services:
    - docker:dind
  image: registry.gitlab.com/etke.cc/base
  script:
    - make login docker
  tags:
    - docker
