project_name: honoroit

builds:
  - main: ./cmd
    binary: honoroit
    goos:
      - freebsd
      - linux
    goarch:
      - arm64
      - amd64

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'

archives:
  - files:
      - CHANGELOG.md
      - LICENSE.md
      - README.md

nfpms:
  - vendor: https://etke.cc
    maintainer: etke.cc
    description: A helpdesk bot
    homepage: https://gitlab.com/etke.cc/honoroit
    license: MIT
    formats:
      - deb
      - rpm
      - apk
